import DS from 'ember-data';
export default DS.Model.extend({

answerChoice:DS.attr(),
question:DS.attr('string'),
questiontype:DS.attr('string'),
difficulty:DS.attr(),
position:DS.attr(),
timer:DS.attr(),
fullscreen:DS.attr(),
inline:DS.attr(),
autonxt:DS.attr(),
enabled:DS.attr(),
srnum:DS.attr(),
}).reopenClass({
  FIXTURES: [
      {
          id:1,
          srnum:1,
          question:"What are the types of linkages?",
          answerChoice:["type-1","type-2","type-3","type-9"],
          questiontype:"MCMA",
          difficulty:"1",
          position:"1",
          timer:"12",
          fullscreen:true,
          inline:false,
          autonxt:true,
          enabled:false,
      },
      {
        id:2,
        srnum:2,
        question:"Which of the following special symbol allowed in a variable name?",
        answerChoice:["@","$","^"],
         questiontype:"MCMA",
         difficulty:"3",
         position:"2",
         timer:"10",
         fullscreen:true,
         inline:true,
         autonxt:false,
         enabled:true,
      },
      {
        id:3,
        srnum:3,
        question:"When we mention the prototype of a function?",
        answerChoice:["at starting","at the end","in exception"],
         questiontype:"MCSA",
         difficulty:"2",
         position:"3",
         timer:"9",
         fullscreen:false,
         inline:true,
         autonxt:true,
         enabled:false,
      },
      {
        id:4,
        srnum:4,
        question:"How would you round off a value from 1.66 to 2.0?",
        answerChoice:["by deleting","by providing new value","to round-off"],
         questiontype:"MCSA",
         difficulty:"3",
         position:"4",
         timer:"5",
         fullscreen:false,
         inline:false,
         autonxt:false,
         enabled:false,
      },
      {
        id:5,
        srnum:5,
        question:"By default a real number is treated as a-",
        answerChoice:["integer","float","double","none of these"],
         questiontype:"MCSA",
         difficulty:"1",
         position:"5",
         timer:"13",
         fullscreen:false,
         inline:true,
         autonxt:true,
         enabled:true,
      },
      {
        id:6,
        srnum:6,
        question:"Which of the following jobs are NOT performed by Garbage Collector?",
        answerChoice:["save memory","free objects","collect variables"],
         questiontype:"MCSA",
         difficulty:"3",
         position:"6",
         timer:"8",
         fullscreen:true,
         inline:false,
         autonxt:true,
         enabled:false,
     },
     {
        id:7,
        srnum:7,
        question:"Explain TCP/IP",
        questiontype:"FREE",
        difficulty:"2",
        position:"7",
        timer:"7",
        fullscreen:false,
        inline:true,
        autonxt:false,
        enabled:true,
    }
  ]
});
